openapi: 3.0.3
info:
  title: Environmental Data Retrieval API's
  description: Example of Candidate Environmental Data Retrieval API OpenAPI docs
  version: 0.0.9
  contact:
    name: "Open Geospatial Consortium (OGC)"
    email: standards-team@ogc.org
    url: 'https://www.ogc.org/contacts'
  license:
    name: OGC License
    url: http://www.opengeospatial.org/legal/
  x-logo:
    url: 'https://www.ogc.org/pub/www/files/OGC_Logo_2D_Blue_x_0_0.png'
servers:
  - url: http://www.example.org/edr
    description: ''
paths:
  "/":
    get:
      tags:
        - Capabilities
      summary: landing page of this API
      description: The landing page provides links to the API definition, the Conformance
        statements and the metadata about the feature data in this dataset.
      operationId: getLandingPage
      responses:
        '200':
          description: links to the API capabilities
          content:
            application/json:
              schema:
                "$ref": https://ghobona.github.io/miscellaneous/openapi/schemas/landingPage.json
            text/html:
              schema:
                type: string
      parameters:
        - "$ref": https://ghobona.github.io/miscellaneous/openapi/parameters/f.json
tags:
  - name: Capabilities
    description: Essential characteristics of the information available from the API.
  - name: Collection metadata
    description: Description of the information available from the collections
  - name: Instance metadata
    description: Description of the information available from instances of a collection
  - name: Collection data queries
    description: Data queries available.
  - name: Instance data queries
    description: Data queries available on instances of the collection.
