openapi: 3.0.2
# Revisions:
# 2019-07-14 Reparated from a more complex domains document
#
info:
  title: OGC API Maps Building Blocks
  description: |-
    Common components used in the OGC API maps standards.

    This document is also available in [GitHub](https://github.com/opengeospatial/OGC-API-Map-Tiles/tree/master/standard/openapi). 

  version: "1.0.0"
  contact:
    name: Joan Maso
    email: joan.maso@uab.cat
  license:
    name: OGC License
    url: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/LICENSE'



components:
  schemas:
    collection-link:
      #This element is not directly linkable by other APIs because they probably will need to add other links to other resource types. Instead, it would be copied and enriched with more examples.
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/link'
          example:
            - $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/examples/link-collection-this'
            - $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/examples/link-collection-describedBy'
            - $ref: '#/components/examples/link-collection-maps'
    maps-link:
      #This element is not directly linkable by other APIs because they probably will need to add other links to other resource types. Instead, it would be copied and enriched with more examples.
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/link'
          example:
            - $ref: '#/components/examples/link-maps-this'
            - $ref: '#/components/examples/link-maps-map'
            - $ref: '#/components/examples/link-maps-info'
    collection:
      # This object does not include the links element that should be added as and additional element using collection-link      
      type: object
      properties:
        styles:
          $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-map-styles/1.0.0#/components/schemas/style-set'
        defaultStyle:
          $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-map-styles/1.0.0#/components/schemas/default-style'
    maps:
      type: object
      properties:
        # A WMS layer definition has id, title, description, keyword that are already defined in OWS Common
        # wgs84BoundingBox is the 'extent' that is already defined in OWS Common
        # BoundingBox is the crsSpatialExtents that is already defined in OWS Common
        # For the moment we will assume that maps can only be produced in the crs's advertised by the collection in the common part.
        minScaleDenominador:
          type: number
          description: |-
            Minimum scale denominator (inclusive) for which it is appropriate to generate a map of this collection. Requests outside this interval will return an HTTP 404. If it is not present we will assume there is no limit.
          example: 10
        maxScaleDenominador:
          type: number
          description: |-
            Maximum scale denominator (inclusive) for which it is appropriate to generate a map of this collection. Requests outside this interval will return an HTTP 404 If it is not present we will assume there is no limit.
          example: 10000000
        #spatialResolution (resx) this should be part of the common metadata but currently is not.
        recomendedFormat:
          type: string
          description: |-
              Recommended output formats for a map request. Depending of the nature of the data, a format might be better than another. Categorical data looks better in a PNG but continuos data and pictures are smaller a JPEG. The map operation details all available formats for the OGC API maps. In contrast, this is the better one for this type of information. It would be one of the supported for the map operation
          example: 'image/jpeg'
        #queryable is not included here because it is indicated by a link with 'rel':'info' but I'm not sure it is the right decision.
        cascaded:
          type: number
          description: |-
            Indicates how main times the collection map has been retransmitted from another map service or API (cascading). It it is not present the collection is not cascaded.
          example: 0
          default: 0
        opaque:
          type: boolean
          description: |-
            Indicates whether the map data represents features that probably do not completely fill space shows the background opaque (true) or transparent(false).
          example: false
          default: false
        noSubsets:
          # this is a very old paramter in WMS and I recommend to deprecate it
          type: boolean
          description: |-
            Indicates whether the server can produce a map that is a subset of the full bounding box.
          example: false
        fixedWidth:
          # this is a very old paramter in WMS and I recommend to deprecate it
          type: number
          description: |-
            Indicates that the server can only produce map of a fixed width instead of an arbitrary width
        fixedHeight:
          # this is a very old paramter in WMS and I recommend to deprecate it
          type: number
          description: |-
            Indicates that the server can only produce map of a fixed height instead of an arbitrary height
    collection-patch:
      type: object
      properties:
        styles:
          $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-map-styles/1.0.0#/components/schemas/style-set'
        defaultStyle:
          type: string
          nullable: true
          description: |-
            the style id of a recommended default style to use for this collection
          example: 'topographic'
  responses:
    tiles:
      description: |-
        Description of the tiles.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/maps'
  parameters:
    bbox:
      name: bbox
      in: query
      description: |-
        Only elements that have a geometry that intersects the bounding box are selected.
        The bounding box is provided as four or six numbers, depending on whether the
        coordinate reference system includes a vertical axis (elevation or depth):

        * Lower left corner, coordinate axis 1
        * Lower left corner, coordinate axis 2
        * Upper right corner, coordinate axis 1
        * Upper right corner, coordinate axis 2

        coordinate
        reference system is specified by another parameter in the API ('crs').

        For WGS 84 longitude/latitude the values are in most cases the sequence of
        minimum longitude, minimum latitude, maximum longitude and maximum latitude.
        However, in cases where the box spans the antimeridian the first value
        (west-most box edge) is larger than the third value (east-most box edge).

      required: false
      schema:
        type: array
        minItems: 4
        maxItems: 4
        items:
          type: number
          format: double
      style: form
      explode: false
    crs:
      name: crs
      in: query
      description: A URI of the coordinate reference system of the bbox and the map subset response. A list of all available CRS values can be found under the map description resource.
      schema:
        type: string
      example:
        'http://www.opengis.net/def/crs/OGC/1.3/CRS84'  
    mapId:
      name: mapId
      in: path
      description: Local identifier of a specific map created with a post operation
      required: true
      style: simple
      explode: false
      schema:
        type: string
    crsId:
      name: crsId
      in: path
      description: |-
        Local identifier of a specific CRS. A list of all available CRSIds can be found under the /CRS path. The default CRS is WGS 84.
      required: true
      schema:
        type: string
      example: WGS84
    width:
      name: width
      in: query
      description: |-
        Width in pixels of map picture.
      required: false
      style: form
      explode: false
      schema:
        type: number
        default: 256
    height:
      name: height
      in: query
      description: |-
        Height in pixels of map picture.
      required: false
      style: form
      explode: false
      schema:
        type: number
        default: 256
    transparent:
      name: transparent
      in: query
      description: |-
        Background transparency of map (default=true).
      required: false
      style: form
      explode: false
      schema:
        type: boolean
        default: true
    bgcolor:
      name: bgcolor
      in: query
      description: |-
        Hexadecimal red-green-blue[-alpha] color value for the background color (default=0xFFFFFF). If alpha is not specified "opaque" opacity is assumed.
      required: false
      style: form
      explode: false
      schema:
        type: string
        default: 0xFFFFFF
    map-crs:
      name: crs
      in: query
      description: |-
        CRSId used to render the map. It is also the CRS of the bbox parameter.
        You can only ask for CRSs that are valid for the collectionId.
      required: false
      style: form
      explode: false
      schema:
        type: string
        example: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
        default: 'http://www.opengis.net/def/crs/EPSG/0/3857'
  examples:
    link-landingPage-maps:
      href: 'http://data.example.org/maps'
      rel: maps
      type: application/json
      title: Link to information on maps combining more than one collection
    link-collection-maps:
      href: 'http://data.example.com/collections/buildings/maps'
      rel: maps
      type: 'application/json'
    link-maps-this:
      href: 'http://data.example.com/collections/buildings/maps'
      rel: self
      type: 'application/json'
    link-maps-map:
      href: 'http://data.example.com/collections/buildings/maps/brown'
      rel: map
      type: 'image/png'
    link-maps-info:
      href: 'http://data.example.com/collections/buildings/maps/brown/info'
      rel: info
      type: 'text/html'
    link-maps-col-this:
      href: 'http://data.example.com/maps'
      rel: self
      type: 'application/json'
    link-maps-col-tile:
      href: 'http://data.example.com/maps/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png'
      rel: tile
      type: 'image/png'
    link-maps-col-info:
      href: 'http://data.example.com/maps/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info'
      rel: info
      type: 'text/html'
